services:
  cassandra:
    build: .
    image: cassandra:3.11
    container_name: cassandra-dev
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      CASSANDRA_ENABLE_USER_DEFINED_FUNCTIONS: true
volumes:
  cassandra_data: